spring:
  port: 8080
  application:
    name: students-app
  datasource:
    url: jdbc:mysql://localhost:3306/products-db?createDatabaseIfNotExist=true
    username: root
    password:
  #    url: jdbc:h2:mem:products-db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  h2:
#    console:
#      enabled: true
